// file: HashSquare.java
// generated by: mashc
// from: HashSquare.mash

public class HashSquare {

protected static final int MAX_INT = java.lang.Integer.MAX_VALUE;

protected static final int MIN_INT = java.lang.Integer.MIN_VALUE;

protected static final long MAX_LONG = java.lang.Long.MAX_VALUE;

protected static final long MIN_LONG = java.lang.Long.MIN_VALUE;

protected static final double PI = java.lang.Math.PI;

private static java.util.Scanner mash_console_scanner 
               = new java.util.Scanner(System.in);

public static void main(java.lang.String[] mash_args_param) 
         throws java.lang.Exception {
            
java.lang.System.out.print("Enter a number: ");
int number = mash_console_scanner.nextInt();
for (int loop2 = 0; loop2 < number; loop2 = loop2 + 1)
{
java.lang.System.out.println("");
for (int loop = 0; loop < number; loop = loop + 1)
{
java.lang.System.out.print("#");
}
}
java.lang.System.out.println("");

         }

}
