// file: Pay.java
// generated by: mashc
// from: Pay.mash

public class Pay {

protected static final int MAX_INT = java.lang.Integer.MAX_VALUE;

protected static final int MIN_INT = java.lang.Integer.MIN_VALUE;

protected static final long MAX_LONG = java.lang.Long.MAX_VALUE;

protected static final long MIN_LONG = java.lang.Long.MIN_VALUE;

protected static final double PI = java.lang.Math.PI;

private static java.util.Scanner mash_console_scanner 
               = new java.util.Scanner(System.in);

public static void main(java.lang.String[] mash_args_param) 
         throws java.lang.Exception {
            
double maxhour = 35;
double overtime = 2;
java.lang.System.out.print("What is your hourly payrate? ");
double rate = mash_console_scanner.nextDouble();
java.lang.System.out.print("How many hours did you work? ");
double hours = mash_console_scanner.nextDouble();
if (hours < maxhour)
{
double pay = rate * hours;
java.lang.System.out.println("Your pay will be: " + pay);
}
else
{
double extra = hours - maxhour;
double bonuspay = (extra * 2) * rate;
double pay = rate * maxhour;
double total = pay + bonuspay;
java.lang.System.out.println("Your pay will be: $" + total);
}

         }

}
