// file: Rot13.java
// generated by: mashc
// from: Rot13.mash

public class Rot13 {

protected static final int MAX_INT = java.lang.Integer.MAX_VALUE;

protected static final int MIN_INT = java.lang.Integer.MIN_VALUE;

protected static final long MAX_LONG = java.lang.Long.MAX_VALUE;

protected static final long MIN_LONG = java.lang.Long.MIN_VALUE;

protected static final double PI = java.lang.Math.PI;

private static java.util.Scanner mash_console_scanner 
               = new java.util.Scanner(System.in);

protected static char toUpperCase(char c)  {
if ('a' <= c && c <= 'm')
{
return (char) (c + 13);
}
else
if ('n' <= c && c <= 'z')
{
return (char) (c - 13);
}
else
if ('A' <= c && c <= 'M')
{
return (char) (c + 13);
}
else
if ('N' <= c && c <= 'Z')
{
return (char) (c - 13);
}
else
{
return c;
}
}

protected static java.lang.String toUpperCase(java.lang.String s)  {
java.lang.String t = "";
for (int i = 0; i < s.length(); i = i + 1)
{
t = t + Rot13.toUpperCase(s.charAt(i));
}
return t;
}

public static void main(java.lang.String[] mash_args_param) 
         throws java.lang.Exception {
            
{
java.lang.System.out.print("Enter a line of text: ");
java.lang.String line = mash_console_scanner.nextLine();
java.lang.System.out.println(("String: ") + line);
java.lang.String temp = Rot13.toUpperCase(line);
java.lang.System.out.println(("Encoded: ") + Rot13.toUpperCase(line));
java.lang.System.out.println(("Decoded: ") + Rot13.toUpperCase(temp));
}

         }

}
