// file: Test.java
// generated by: mashc
// from: Test.mash

public class Test {

protected static final int MAX_INT = java.lang.Integer.MAX_VALUE;

protected static final int MIN_INT = java.lang.Integer.MIN_VALUE;

protected static final long MAX_LONG = java.lang.Long.MAX_VALUE;

protected static final long MIN_LONG = java.lang.Long.MIN_VALUE;

protected static final double PI = java.lang.Math.PI;

private static java.util.Scanner mash_console_scanner 
               = new java.util.Scanner(System.in);

protected static char toUpperCase(char c)  {
if ('a' <= c && c <= 'z')
{
return (char) (c - 'a' + 'A');
}
else
{
return c;
}
}

protected static java.lang.String toUpperCase(java.lang.String s)  {
java.lang.String t = "";
for (int i = 0; i < s.length(); i = i + 1)
{
t = t + Test.toUpperCase(s.charAt(i));
}
return t;
}

public static void main(java.lang.String[] mash_args_param) 
         throws java.lang.Exception {
            
{
java.lang.System.out.println(Test.toUpperCase('a'));
java.lang.System.out.println(Test.toUpperCase('b'));
java.lang.System.out.println(Test.toUpperCase('z'));
java.lang.System.out.println(Test.toUpperCase('A'));
java.lang.System.out.println(Test.toUpperCase(';'));
java.lang.System.out.println(Test.toUpperCase('9'));
java.lang.System.out.println(Test.toUpperCase(""));
java.lang.System.out.println(Test.toUpperCase("a"));
java.lang.System.out.println(Test.toUpperCase("abzA;9"));
}

         }

}
